# ======================================================================
# GATEWAY - Distributed Configuration (Config Server)
# Environment-driven, safe for local/dev/prod
# ======================================================================

server:
  port: ${GATEWAY_PORT:8080}

spring:
  application:
    # DO NOT use env placeholders here — bootstrap must always succeed
    name: gate-way

  data:
    redis:
      host: ${GATEWAY_REDIS_HOST:localhost}
      port: ${GATEWAY_REDIS_PORT:6379}
      timeout: ${GATEWAY_REDIS_TIMEOUT:2000}

  cloud:
    gateway:

      # ---------------------------------------------------------------
      # JWT Signature Configuration
      # ---------------------------------------------------------------
      jwt:
        secret: ${GATEWAY_JWT_SECRET}
        allowed-skew: ${GATEWAY_JWT_ALLOWED_SKEW:5000}

      # ---------------------------------------------------------------
      # Spring Cloud Gateway 4.x Route Architecture (WebFlux)
      # ---------------------------------------------------------------
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

          routes:
            user:
              path: ${GATEWAY_USER_PATH:/auth/**}
              service-id: ${GATEWAY_USER_SERVICE_ID:user-service}

            wallet:
              path: ${GATEWAY_WALLET_PATH:/wallet/**}
              service-id: ${GATEWAY_WALLET_SERVICE_ID:wallet-service}

            transaction:
              path: ${GATEWAY_TRANSACTION_PATH:/transaction/**}
              service-id: ${GATEWAY_TRANSACTION_SERVICE_ID:transaction-service}

      # ---------------------------------------------------------------
      # CORS Configuration
      # ---------------------------------------------------------------
      cors:
        allowed-origins: ${GATEWAY_ALLOWED_ORIGINS:http://localhost:3000}
        allowed-methods: ${GATEWAY_ALLOWED_CORS_METHODS:GET,POST,PUT,DELETE}
        allowed-headers: ${GATEWAY_ALLOWED_CORS_HEADERS:Authorization,Content-Type}
        allow-credentials: ${GATEWAY_CORS_ALLOW_CREDENTIALS:true}

      # ---------------------------------------------------------------
      # Security & Custom Headers
      # ---------------------------------------------------------------
      security:
        open-endpoints: ${GATEWAY_OPEN_ENDPOINTS:/auth/login,/auth/register}
        header:
          username: ${GATEWAY_HEADER_USERNAME:x-username}
          user-id: ${GATEWAY_HEADER_USER_ID:x-user-id}
          role: ${GATEWAY_HEADER_ROLE:x-role}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}
