server:
  # Gateway inbound port
  port: ${GATEWAY_PORT}

spring:
  application:
    # Logical service name for Eureka registration
    name: ${SPRING_APPLICATION_GATEWAY_NAME}

  # ----------------------------------------------------------------------
  # Redis Connection (Used by Spring Cloud Gateway RateLimiter)
  # ----------------------------------------------------------------------
  data:
    redis:
      host: ${GATEWAY_REDIS_HOST}   # redis container name OR localhost
      port: ${GATEWAY_REDIS_PORT}   # default 6379
      timeout: ${GATEWAY_REDIS_TIMEOUT}  # recommended 2000-5000ms

  cloud:
    gateway:

      # ------------------------------------------------------------------
      # JWT Signature + Time Skew Settings
      # ------------------------------------------------------------------
      jwt:
        secret: ${GATEWAY_JWT_SECRET}
        allowed-skew: ${GATEWAY_JWT_ALLOWED_SKEW:5000} # Prevents minor clock drift issues

      # ------------------------------------------------------------------
      # SCG 4.x WebFlux Route Model
      # No RouteDefinition YAML format allowed in 4.x
      # ------------------------------------------------------------------
      server:
        webflux:
          discovery:
            locator:
              enabled: false           # You are using manual RouteLocatorConfig
              lower-case-service-id: true

          # Route definitions (for RouteLocator)
          routes:

            user:
              path: ${GATEWAY_USER_PATH}           # e.g., /auth/**
              service-id: ${GATEWAY_USER_SERVICE_ID}

            wallet:
              path: ${GATEWAY_WALLET_PATH}         # e.g., /wallet/**
              service-id: ${GATEWAY_WALLET_SERVICE_ID}

            transaction:
              path: ${GATEWAY_TRANSACTION_PATH}    # e.g., /transaction/**
              service-id: ${GATEWAY_TRANSACTION_SERVICE_ID}

      # ------------------------------------------------------------------
      # CORS Configuration
      # Applied globally across all downstream services
      # ------------------------------------------------------------------
      cors:
        allowed-origins: ${GATEWAY_ALLOWED_ORIGINS}     # Frontend origin
        allowed-methods: ${GATEWAY_ALLOWED_CORS_METHODS}
        allowed-headers: ${GATEWAY_ALLOWED_CORS_HEADERS}
        allow-credentials: ${GATEWAY_CORS_ALLOW_CREDENTIALS}

      # ------------------------------------------------------------------
      # Security Settings (Custom Headers injected post-JWT validation)
      # ------------------------------------------------------------------
      security:
        open-endpoints: ${GATEWAY_OPEN_ENDPOINTS} # Comma-separated paths bypassing filter
        header:
          username: ${GATEWAY_HEADER_USERNAME}
          user-id: ${GATEWAY_HEADER_USER_ID}
          role: ${GATEWAY_HEADER_ROLE}
