# ======================================================================
# GATEWAY - Distributed Configuration (Config Server)
# Environment-driven, safe for local/dev/prod
# ======================================================================

server:
  port: ${GATEWAY_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_GATEWAY_NAME}

  data:
    redis:
      host: ${GATEWAY_REDIS_HOST}  
      port: ${GATEWAY_REDIS_PORT}  
      timeout: ${GATEWAY_REDIS_TIMEOUT} 

  cloud:
    gateway:

      jwt:
        secret: ${GATEWAY_JWT_SECRET}
        allowed-skew: ${GATEWAY_JWT_ALLOWED_SKEW:5000}


      server:
        webflux:
          discovery:
            locator:
              enabled: false           
              lower-case-service-id: true
          routes:

            user:
              path: ${GATEWAY_USER_PATH}           # e.g., /auth/**
              service-id: ${GATEWAY_USER_SERVICE_ID}

            wallet:
              path: ${GATEWAY_WALLET_PATH}         # e.g., /wallet/**
              service-id: ${GATEWAY_WALLET_SERVICE_ID}

            transaction:
              path: ${GATEWAY_TRANSACTION_PATH}    # e.g., /transaction/**
              service-id: ${GATEWAY_TRANSACTION_SERVICE_ID}

      cors:
        allowed-origins: ${GATEWAY_ALLOWED_ORIGINS}   
        allowed-methods: ${GATEWAY_ALLOWED_CORS_METHODS}
        allowed-headers: ${GATEWAY_ALLOWED_CORS_HEADERS}
        allow-credentials: ${GATEWAY_CORS_ALLOW_CREDENTIALS}


      security:
        open-endpoints: ${GATEWAY_OPEN_ENDPOINTS} 
        header:
          username: ${GATEWAY_HEADER_USERNAME}
          user-id: ${GATEWAY_HEADER_USER_ID}
          role: ${GATEWAY_HEADER_ROLE}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL}
  instance:
    hostname: localhost
    non-secure-port: ${server.port}
    prefer-ip-address: true
