server:
  port: ${USER_SERVICE_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_USER_SERVICE_NAME}

  datasource:
    url: ${USER_SERVICE_DB_URL}
    username: ${USER_SERVICE_DB_USERNAME}
    password: ${USER_SERVICE_DB_PASSWORD}
    driver-class-name: ${USER_SERVICE_DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: ${USER_SERVICE_JPA_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${USER_SERVICE_HIBERNATE_DIALECT}
        "[show_sql]": ${USER_SERVICE_HIBERNATE_SHOW_SQL}

  kafka:
    producer:
      bootstrap-servers: ${USER_SERVICE_KAFKA_SERVERS}
      key-serializer: ${USER_SERVICE_KAFKA_KEY_SERIALIZER}
      value-serializer: ${USER_SERVICE_KAFKA_VALUE_SERIALIZER}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
